"""Initial migration

Revision ID: 9032d2a1061a
Revises: 56a1725e748d
Create Date: 2026-05-29 16:12:43.547745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9032d2a1061a'
down_revision: Union[str, Sequence[str], None] = '56a1725e748d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.drop_column('categories', 'is_publieshed')
    op.add_column('locations', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.drop_column('locations', 'is_publieshed')
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.drop_column('posts', 'is_publieshed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_publieshed', sa.BOOLEAN(), nullable=False))
    op.drop_column('posts', 'is_published')
    op.add_column('locations', sa.Column('is_publieshed', sa.BOOLEAN(), nullable=False))
    op.drop_column('locations', 'is_published')
    op.add_column('categories', sa.Column('is_publieshed', sa.BOOLEAN(), nullable=False))
    op.drop_column('categories', 'is_published')
    # ### end Alembic commands ###
